SOCIAL_AUTH_TWITTER_KEY = 'change me'
SOCIAL_AUTH_TWITTER_SECRET = 'change me'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = 'change me'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'change me'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/'